### ISSUE TITLE
Packet loss occurs in the published message

### ISSUE THREAD

**Issue by akon99** [aler9/goroslib#107]
I used the demo in publisher-custom and subscribe-custom, and added a timestamp before publishing the message. Then I found that the message subscribed by the subscriber has packet loss, which may be a bug, so I would like to ask you to take a look and provide a solution. This matter is urgent, and we look forward to your reply，Attachment is my code and log，
My PC :Ubuntu:18.04
ROS:
SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
go version go1.18.1 linux/amd64

[logAndCode.zip](https://github.com/aler9/goroslib/files/8926295/logAndCode.zip)

**Comment by aler9** [comment]
Thanks for reporting this issue, it has been fixed.
