### ISSUE TITLE
Unable to see topic frequency

### ISSUE THREAD

**Issue by Filea** [aler9/goroslib#11]
Good afternoon. 

First of all, thank you for your work and the fantastic library you have made available to the ROS community.
I was playing with the test files that you provide and I notice that it is not possible to see the frequency with which topics are published. I believe that's a bug.

Best regards, 
Filipe Pinto

**Comment by aler9** [comment]
Hi, thanks for the report, this library is now compatible with `rostopic hz`.
Let me know if there are more problems.
