### ISSUE TITLE
ServiceClient.Call() need concurrency support

### ISSUE THREAD

**Issue by arboat** [aler9/goroslib#112]
## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

The client side gets  "EOF" errors  when call  ServiceClient.Call()  concurrently, meanwhile the server side print : 

```
[ERROR] service provider '/test/xxxx' is unable to accept client '127.0.0.1:xxx': a client with id '/xxx' is already connected to the provider
```
It seems that this go ros package is not support concurrency? Would you please look into this problem, and give me some help to let me successfully call the function concurrently. Thanks a lot.

**Comment by aler9** [comment]
Thanks, now `ServiceClient.Call()` is thread-safe.

**Comment by sniperZj** [comment]
@aler9 I updated it and the latest version will still appear

**Comment by arboat** [comment]
@aler9 
Hello, I see you add mutex.Lock in the Call() method, actually it runs  sequentially. I used waitgroup to setup 1000 goroutines to call the method, and  it cost a lot of time.   So is there any possible to let the ros communication itself run  concurrently? Look forwarding for your reply. Thank you.

**Comment by aler9** [comment]
> is there any possible to let the ros communication itself run concurrently?

You can't use a single connection to write requests and read responses concurrently, it's a limit shared by both ROS services and HTTP. 

Nonetheless, you can obtain concurrency by using a different `ServiceClient` in each goroutine.
