### ISSUE TITLE
use rospy serviceProxy cycle call service err

### ISSUE THREAD

**Issue by sniperZj** [aler9/goroslib#116]
## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [x] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
roslog: service provider '/data/get_cabinet_ext_data' is unable to accept client '127.0.0.1:58296': a client with id '/test_client_31708_1665221359122' is already connected to the provider

rospy.ServiceException:
Service call failed: unable to connect to service: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

code:
#!/usr/bin/env python

import rospy
import rail_mounted_robot_msgs.srv

def call_get_cabinet_ext_data(room, cabinet):
    rospy.wait_for_service('data/get_cabinet_ext_data')
    try:
        get_cabinet_ext_data = rospy.ServiceProxy('data/get_cabinet_ext_data', rail_mounted_robot_msgs.srv.GetCabinetExtData)
        resp = get_cabinet_ext_data(cabinet, room)
        return resp.cabinet_name
    except rospy.ServiceException as e:
        print('Service call failed: {}'.format(e))

if __name__ == "__main__":
    rospy.init_node('test_client', anonymous=True)
    while not rospy.is_shutdown():
        call_get_cabinet_ext_data('20200331', '')

**Comment by sniperZj** [comment]
service golib is the latest version

**Comment by sniperZj** [comment]
@aler9 help

**Comment by aler9** [comment]
Hello, goroslib's ServiceProvider is now able to accept multiple connections from the same node. Anyway, a node should instantiate ServiceProxy / ServiceClient once and reuse it, that error message is caused by the fact that ServiceProxy / ServiceClient was instantiated twice.

**Comment by sniperZj** [comment]
@aler9 Thank you
