### ISSUE TITLE
service client custom timeout

### ISSUE THREAD

**Issue by wzbooks** [aler9/goroslib#135]
## Describe the feature

Hello, can the service client support custom timeout Settings? We have a service provider that takes a long time to process, about 56 seconds, and will prompt a i/o timeout after call

**Comment by aler9** [comment]
Hello, i've added parameters `NodeConf.ReadTimeout` and `NodeConf.WriteTimeout` in order to allow users to set timeouts. They are available in v1.2.0.

**Comment by wzbooks** [comment]
That's great. Thank you so much
