### ISSUE TITLE
Subscriber doesn't deliver messages with Definitions

### ISSUE THREAD

**Issue by knuesel** [aler9/goroslib#18]
I have a topic in a bag where messages include an `actionmsgs.GoalStatus` field. The subscriber doesn't deliver any message. It seems that the problem comes from the `Definitions` in `GoalStatus`.

Here's a simple way to reproduce the issue: in `publisher-custom.go` and `subscriber-custom.go`, add ```msgs.Definitions `ros:"uint8 A=0,uint8 B=1"` ``` in the definition of `TestMessage`. Then the subscriber won't show any message.

**Comment by aler9** [comment]
messages with definitions can now be written and received, thanks.

**Comment by knuesel** [comment]
Thanks for the quick fix!
