### ISSUE TITLE
ROS CLI - unable to determine type of service 

### ISSUE THREAD

**Issue by MKervo** [aler9/goroslib#2]
Hi,
Thanks for your work ! I was looking how to build lightweight nodes in Go.  

I'm using ROS Melodic
Right now, I'm trying to implement a basic service client/provider. I did as the examples says.
But I can't make them communicate with each others.
```
Error: lookupService: server returned an error (-1): no provider
```
Also, when I'm using `rosnode` and `rosservice` and use `list` I've got a double slash prefix.
```bash
$ rosnode list
//node_name
$ rosservice list
//service_name
```
I can't call them or get any infos. They seems to be unknown or corrupt in some way.

Any ideas what's going on ?

**Comment by aler9** [comment]
Hello, i wasn't able to replicate the bug. I did the following:

1. in one terminal i launched ROS melodic
    ```
    docker run --rm -it --network=host --name=ros ros:melodic-ros-core-bionic roscore
    ```

2. in another terminal i launched the `serviceprovider.go` example
    ```
    docker run --rm -it --network=host golang:1.13 sh -c "git clone https://github.com/aler9/goroslib && cd goroslib && go run examples/serviceprovider.go"
    ```

3. in another terminal i checked `rosnode list` and `rosservice list`
    ```
    docker exec -it ros bash -c "source /opt/ros/melodic/setup.bash && rostopic list && rosservice list"
    ```

the output is
```
/test_srv
```

can you provide the .go source you used to perform the test?
