### ISSUE TITLE
run examples/serviceclient.go failed

### ISSUE THREAD

**Issue by JiHongzhou** [aler9/goroslib#21]
* /rosdistro: melodic
 * /rosversion: 1.14.9

I got an panic log as follow:
panic: lookupService: server returned an error (-1): no provider

goroutine 1 [running]:
main.main()
	/home/goroslib/examples/serviceclient.go:45 +0x3fb

**Comment by JiHongzhou** [comment]
When I change  node name to "goroslibsc", It's OK. So I think we cannot set the same name with serviceClient and ServiceProvider.

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, the examples have been updated to use different node names.
