### ISSUE TITLE
NewServiceClient failed when ServiceProvider is not exist

### ISSUE THREAD

**Issue by JiHongzhou** [aler9/goroslib#23]
Whne I startup a serviceclient, the client will exit with an error "no provider". That is different with "CPP". 

What is your idea about this？Why do you call LookupService when NewServiceClient?

**Comment by aler9** [comment]
Hello, i finally got the time to analyze this issue; the reference CPP implementation does this:
* a service client can be created before a service provider is created
* a service client requests the list of available providers during every request, allowing providers to connect and disconnect dinamically

Therefore, the behavior of this library will be changed accordingly.

**Comment by aler9** [comment]
done
