### ISSUE TITLE
 Dropping connection issue with Client [/goroslib-sub]

### ISSUE THREAD

**Issue by vibin18** [aler9/goroslib#26]
**Connection drop error while subscribing `/diagnostics` on ROS melodic. **

```ERROR] [1605789975.048534337]: Client [/goroslib-sub] wants topic /diagnostics to have datatype/md5sum [diagnostic_msgs/DiagnosticArray/009ab8ab4fe239b91b7cff4869b68b68], but our version has [diagnostic_msgs/DiagnosticArray/60810da900de1dd6ddd437c3503511da]. Dropping connection.```

**### Versions:-**
golang   1.15.2 windows/amd64
ROS melodic

_code:-_

```golang

import (
	"fmt"
	"github.com/aler9/goroslib"
	"github.com/aler9/goroslib/pkg/msgs/diagnostic_msgs"
)

func setDiagMessages(val *diagnostic_msgs.DiagnosticArray) {
	fmt.Println(val)

}

func main() {
	n, err := goroslib.NewNode(goroslib.NodeConf{
		Name:       "/goroslib-sub",
		MasterHost: MASTER,
	})
	if err != nil {
		panic(err)
	}
	defer n.Close()

	sub, err := goroslib.NewSubscriber(goroslib.SubscriberConf{
		Node:     n,
		Topic:    "/diagnostics",
		Callback: setDiagMessages,
	})
	if err != nil {
		panic(err)
	}
	defer sub.Close()

	// freeze main loop
	select {}
}
```

**Comment by aler9** [comment]
Hello, thank you very much for reporting this issue; this was caused by the fact that `byte` definitions were silently replaced with `int8` definitions, so the message DiagnosticStatus
```
byte OK=0
byte WARN=1
byte ERROR=2
byte STALE=3
byte level
string name
string message
string hardware_id
diagnostic_msgs/KeyValue[] values
```
was wrongly defined as
```
int8 OK=0
int8 WARN=1
int8 ERROR=2
int8 STALE=3
int8 level
string name
string message
string hardware_id
diagnostic_msgs/KeyValue[] values
```

now it's fixed.
