### ISSUE TITLE
Support Action Servers ?

### ISSUE THREAD

**Issue by cckui** [aler9/goroslib#32]
Hello , Do you have plan to support action servers ?

Thank you !

**Comment by aler9** [comment]
Hello, they are missing and they will be implemented. Of course a PR is always welcome.

**Comment by aler9** [comment]
Action clients and actions servers have been implemented in main after a long work :-)
What is still missing is
* simple action clients
* simple action servers

**Comment by aler9** [comment]
actions and simple actions have been implemented. Examples are available in the `examples/` folder.

**Comment by cckui** [comment]
@aler9  Thank you very much.
