### ISSUE TITLE
Unable to retrieve service info

### ISSUE THREAD

**Issue by timanema** [aler9/goroslib#35]
Hello again! Thanks for fixing my last issue fairly quickly, this time I'm back with a smaller issue.  
While testing a few ROS services created with goroslib, I noticed that the created services don't work with `rosservice info` and `rosservice call` (and possibly others). Trying either of those commands will return a cryptic python error, suggesting the connection is broken.
This doesn't happen with regular clients (at least goroslib and rospy), but can still be annoying during testing. 

This can be reproduced with docker (or alternatively by running the example code and doing `rosservice ...` on an Ubuntu install). First run ros:
```bash
docker run -it --network=host --name=ros ros:noetic-ros-core roscore
```
Then start the example (in a new terminal):
```bash
docker run --rm -it --network=host golang:1.15 sh -c "git clone https://github.com/aler9/goroslib && cd goroslib && go run examples/serviceprovider.go"
```
Finally, run either info or call (in a new terminal):
```bash
docker exec -it ros bash -c "source /opt/ros/noetic/setup.bash && rosservice info /test_srv"
docker exec -it ros bash -c "source /opt/ros/noetic/setup.bash && rosservice call /test_srv '{data: false}'"
```
The final commands will give you something along the lines of:
```
Traceback (most recent call last):
  File "/opt/ros/noetic/bin/rosservice", line 35, in <module>
    rosservice.rosservicemain()
  File "/opt/ros/noetic/lib/python3/dist-packages/rosservice/__init__.py", line 741, in rosservicemain
    _rosservice_cmd_info(argv)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosservice/__init__.py", line 708, in _rosservice_cmd_info
    _rosservice_info(name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosservice/__init__.py", line 301, in _rosservice_info
    t = get_service_type(service_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosservice/__init__.py", line 147, in get_service_type
    return get_service_headers(service_name, service_uri).get('type', None)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosservice/__init__.py", line 124, in get_service_headers
    return rosgraph.network.read_ros_handshake_header(s, BufferType(), 2048)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
```

I believe the fix is relatively straightforward. First `serviceprovider.go` will have to be changed (lines 159-162) to allow for a wildcard hash (similarly to `publisher.go` at line 314-317):
```golang
if req.header.Md5sum != "*" && req.header.Md5sum != sp.srvMd5 {
  eq.conn.Close()
  continue
}
```
Furthermore, the `Type` header at line 169 is now hardcoded to `goroslib/Service`, but it seems this header is used by `rosservice` to determine the type of the service. I'm no expert, but it seems this header is not used/ignored by goroslib and rospy, so that's why it works without problems for those clients.   
I can think of a few solutions. You could try to deduce the type from the request and response types (which would then need to follow the `<type>Req/Res` scheme), but this would impose restrictions on all users, so not a big fan of this one. Another option would be to keep the currently hardcoded value as a default, but allow users to override it. I'll leave it up to you to think of a nice solution for this one.

**Comment by aler9** [comment]
Hello, thanks for reporting this issue
* the format of service structs was changed to make room for name and package
* rosservice info and rosservice call are now supported

These issues are due to the fact that there are a lot of secondary functions which i never used - i started working with ROS during my thesis, but evidently i'm still missing something.
