### ISSUE TITLE
Time API

### ISSUE THREAD

**Issue by gwaxG** [aler9/goroslib#38]
Hello,
does this library support time API as in Python?
For example, are there similar constructions to get time like `rospy.get_time()`?
There is no problem with reality where we can use system time. 
But simulation time is different from the latter, therefore I wonder how could we get it.

**Comment by aler9** [comment]
Hello, simulated clocks are currently supported but they may be in the future.

**Comment by aler9** [comment]
A Time API, which supports simulated clocks, has been added.

You can now use
```
node.TimeNow()
node.TimeSleep(duration)
node.TimeRate(duration)
```

**Comment by gwaxG** [comment]
Thank you for very quick feature implementation!

**Comment by aler9** [comment]
At the moment you have to set NodeConf's `UseSimTime` to `true` to switch to a simulated clock, but this option will be removed soon and clock seleciton will be automatic.
