### ISSUE TITLE
Topics aren't removed from the ROS master topic list on normal node Shutdown

### ISSUE THREAD

**Issue by Mohamedemad4** [aler9/goroslib#60]
## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
Topics aren't removed from the ROS master topic list on normal node Shutdown (SIGTERM)
this also applies to things like node name.

**Comment by aler9** [comment]
Hello, i checked and it's true that the reference C++ library does listen on SIGTERM and removes topics from the master. Probably it's better to implement this feature in Go too instead of relying on defer().

**Comment by aler9** [comment]
All the examples have been upgraded to correctly handle CTRL-C / SIGINT / SIGTERM, and shutdown the node thereafter.
In this way, users can choose to listen on OS signals like the standard library, or not to, since it causes quite a mess in case of complex programs with multiple objects.
