### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by romainreignier** [aler9/goroslib#7]
Does this port should work on Windows?

I have successfully [cross-compiled](https://github.com/golang/go/wiki/WindowsCrossCompiling) a subscriber and publisher for Windows and run them on a Windows computer on the same network than an Ubuntu box with a ROS master.

The new nodes show up in `rosnode list` but even by supplying correct `MasterHost` in the node constructor, no message are passing.

I have disabled the firewall on the Windows side.

But before digging further, I wanted to know if it is supposed to work on Windows or not.

For me, Windows support would be a major feature because I would be able to easily compile Windows static binaries of ROS nodes from Linux and with a single binary file to deploy.

**Comment by aler9** [comment]
Hello, i tested this scenario, and i can say that cross-compiled nodes, compiled against the latest version of the library, do indeed works on Windows. I tested both the subscriber and the publisher examples.

I was able to make this work after discovering that Windows nodes were getting an IP from the wrong interface. Now the node IP is taken from the same subnet of the master, and that did the trick. It's still possible to set a manual IP, through the Host configuration parameter.
