### ISSUE TITLE
simpleactionclient demo OnDone Wrong number of parameters

### ISSUE THREAD

**Issue by sniperZj** [aler9/goroslib#70]
## Which operating system are you using?

OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [X] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

simpleactionclient OnDone Wrong number of parameters because OnDone must accept 2 arguments

**Comment by aler9** [comment]
Hello, i didn't understood the issue at first, but then i realized that the `OnDone` callback into the `simpleactionclient` example had invalid arguments. This has been fixed, thanks for the report.

**Comment by sniperZj** [comment]
@aler9 you're welcome. thank you for providing such an excellent roslib.
