### ISSUE TITLE
Context support when calling services?

### ISSUE THREAD

**Issue by merlinran** [aler9/goroslib#98]
### Description
I encountered cases when the ROS service misbehaved or network disrupted, the client just hung forever. I wonder if it's a good idea to add a new method `ServiceClient.CallContext` or alike to allow timeout and cancellation on a per-call basis? Currently I wrap the call with context by myself, but since there's no timeout in this library, it could pile up a lot of coroutines.

Didn't read through the code, but I guess `ReadServiceResState` https://github.com/aler9/goroslib/blob/main/pkg/prototcp/conn.go#L57 would be one place to retrofit. @aler9 if you generally agree, I probably can draft a PR sometime.

**Comment by aler9** [comment]
Hello, thanks for reporting the "forever hanging" situation, timeouts have been added everywhere, furthermore `serviceclient.CallContext()` has been implemented.
